KERNEL_OBJECTS := $(patsubst $(KERNEL_SRCDIR)/%.c, $(KERNEL_BUILDDIR)/%.o, $(KERNEL_SOURCES))

UTILS_OBJECTS := $(patsubst $(UTILS_SRCDIR)/%.c, $(UTILS_BUILDDIR)/%.o, $(UTILS_SOURCES))

ARCH_C_OBJECTS := $(patsubst $(ARCH_SRCDIR)/%.c, $(ARCH_BUILDDIR)/%.o, $(ARCH_C_SOURCES))

ARCH_ASM_OBJECTS := $(patsubst $(ARCH_SRCDIR)/%.asm, $(ARCH_BUILDDIR)/%.o, $(ARCH_ASM_SOURCES))

ARCH_OBJECTS := $(ARCH_C_OBJECTS) $(ARCH_ASM_OBJECTS)

ALL_OBJECTS := $(KERNEL_OBJECTS) $(UTILS_OBJECTS) $(ARCH_OBJECTS)